
import "./styles/globals.css";


export const metadata = {
  title: "Clube do Mesário",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
